config/routes.rb
KwbutlerInvite::Application.routes.draw do
  get "welcome/index"
  root to: "welcome#index"

  resources :emails, only: [:create]

  

end

app/models/email.rb
class Email < ActiveRecord::Base
	validates_format_of :email, :with => /@/
	validates_uniqueness_of :email
	validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  def create
  	@email = Email.new email_params

  	if @email.save
  		flash[:notice] = "Thanks! You'll be informed immediately when this service will be available."
  	else
  		flash[:notice] = @email.errors.full_messages.first
  	end
  	redirect_to root_url
  end

  private

  def email_params
    params.require(:email).permit(:email)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@email = Email.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Keyword Butler</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
 
</script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<div class="row hmz">
	<div class="stripe pagination-centered text-center">
		<div class="span7custom-nav">
		</div>
        <div class="span9 custom-content center wide-column">
        	<h1 class="title">Email Collector</h1>
        </div>
	 </div>
</div>

<div class="container center black">
	<br> <br> <br>
	<h3 class="text-center"></h3><br>
    <h1 class="text-center leave-it">Give me your email!</h1>
		    <div id="email-area">
			    <%= form_for @email, url: emails_path do |f| %>
					  <%= f.text_field :email, :class => "span3 input-email", :placeholder => "E-mail" %>
					  <%= button_tag(:class => "btn btn-primary btn-wide mll text-center submit-button btn-inverse") do %>
						  <i class='fui-mail'></i> Notify me when things will be available!
						<% end %>
					<% end %>
					<% unless flash.empty? %>
						<div class="alert alert-info">
							<% flash.each do |name, msg| %>
					      <%= content_tag :div, msg, class: name %>
					    <% end %>
				  	</div>
				  <% end %>
				</div>
</div>
	
	</div>
</div>